name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run Chrome
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          headless: true
          group: ${{ matrix.browser }}
          browser: ${{ matrix.browser }}
          start: yarn start:nobrowser
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
